// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClace_VXa6eYk-ON2wuXeKDPBvpnIuLCo',
    appId: '1:548516437918:android:4857f6191a651e99fc408f',
    messagingSenderId: '548516437918',
    projectId: 'youtube-clone-hammerwar',
    storageBucket: 'youtube-clone-hammerwar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc0mFwdxGOwyzXLzHyTf2CgQe3234-5rE',
    appId: '1:548516437918:ios:adfc715ac161d5acfc408f',
    messagingSenderId: '548516437918',
    projectId: 'youtube-clone-hammerwar',
    storageBucket: 'youtube-clone-hammerwar.firebasestorage.app',
    androidClientId: '548516437918-0ej0i9dj27pv3e0hovdg8ng6aog0ko1q.apps.googleusercontent.com',
    iosClientId: '548516437918-7t3chimgdo07kck1k7vohs8a4c5mi4vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.youtubeClone',
  );
}
